### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by mdevlamynck** [abradley2/elm-datepicker#2]
Hi, would it be possible to allow the datepicker to show dates in other languages? I specifically need it to be in french but it should be possible to select any language. I don't know how to achieve that though. What's your opinion on this?

**Comment by abradley2** [comment]
That's very possible! Just a matter of moving  the month names to the props so they can be configurable. I'll add that in

**Comment by mdevlamynck** [comment]
Maybe using a package like http://package.elm-lang.org/packages/rluiten/elm-date-extra/9.3.1/ can help.

**Comment by abradley2** [comment]
Heya! In the current release I added some configuration properties for localization.

`monthDisplay`, `daySymbol`, and `selectedDateDisplay` each take arguments like `Time.Month`, `Time.Weekday` and `Date` arguments (via [elm/time](https://package.elm-lang.org/packages/elm/time/latest/) and [justinmimbs/date](https://package.elm-lang.org/packages/justinmimbs/date/latest/) packages) and allow you to set whatever `String` representation of this you wish.

["Props"](https://package.elm-lang.org/packages/abradley2/elm-datepicker/latest/DatePicker#Props) section of the docs.

So for a Danish calendar you can do something like

```
toDanishMonth : Month -> String
toDanishMonth month =
  case month of
    Jan -> "januar"
    Feb -> "februar"
    Mar -> "marts"
    Apr -> "april"
    May -> "maj"
    ... etc, etc

toDanishDaySymbol : Day -> String
toDanishDaySymbol day =
  Mon -> "Ma"
  Tue -> "Ti"
  Wed -> "On"
  Thu -> "To"
  Fri -> "Fr"
  ... etc, etc

datePickerProps =
  let props = DatePicker.defaultProps
  in
    { props 
    | monthDisplay = toDanishMonth
    , daySymbol = toDanishDaySymbol
    }
```

And the `selectedDateDisplay` property lets you format the big display date on the header for whatever is selected.

There might be some other cultural differences I can allow configuration for, like the display week not always starting on "Sunday" and instead "Monday". I'll have to do more research around international calendars for that, but do plan on adding support for it!
