### ISSUE TITLE
regression - cannot select year

### ISSUE THREAD

**Issue by panthershark** [abradley2/elm-datepicker#3]
It looks like the year picker capability has been omitted in the latest version.

**Comment by abradley2** [comment]
Yeah. In my rush to get it ready for 0.19 I omitted that functionality in the initial release. Plan on adding it in back shortly. Thanks for the input!

**Comment by abradley2** [comment]
Should be fixed in the latest `4.0.0` release which is out now. Thank you for the PR!

**Comment by panthershark** [comment]
Sweet!  Thanks for merging and publishing!

**Comment by abradley2** [comment]
Closing as fixed :tada:
